apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: ctp
  labels:
    app: ctp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ctp
  template:
    metadata:
      labels:
        app: ctp
    spec:
      containers:
        - name: ctp
          image: adamtravis/rollouts:red
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
  strategy:
      canary:
        steps:
        - setWeight: 20
        - pause: {}
        - setWeight: 40
        - pause:
            duration: 60
        - setWeight: 60
        - pause:
            duration: 60
        - setWeight: 80
        - pause:
            duration: 60
