apiVersion: v1
kind: Service
metadata:
    name: ctp
spec:
    type: LoadBalancer
    ports:
     - targetPort: http
       port: 8080
       nodePort: 31050
       protocol: TCP
    selector:
      app: ctp
